[package]
name = "files"
description = "File system utilities and constants."
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

base64 = "0.22.1"
directories = "6.0.0"
flate2 = "1.0.35"
