on:
  # debug check
  push:
    branches: "**"
  pull_request: 
    types:
      - opened
      - edited

jobs:
  build:
    name: check ${{ matrix.target }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-pc-windows-gnu
          - x86_64-unknown-linux-musl
          - x86_64-apple-darwin

    steps:
      - uses: actions/checkout@master

      - name: Add target
        run: rustup target add ${{ matrix.target }}

      - name: Clippy check
        uses: actions-rs/clippy-check@v1.0.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --target=${{ matrix.target }}
